/
// Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
//
// On Tue Feb 11 15:21:37 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 unused
// RST_N                          I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTestbench(CLK,
		   RST_N);
  input  CLK;
  input  RST_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_print_answer, WILL_FIRE_RL_rl_print_answer;

  // rule RL_rl_print_answer
  assign CAN_FIRE_RL_rl_print_answer = 1'd1 ;
  assign WILL_FIRE_RL_rl_print_answer = 1'd1 ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    $display("Deep Thought says: Hello, World! The answer is 42.");
    $finish(32'd1);
  end
  // synopsys translate_on
endmodule  // mkTestbench